name: screens
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  crypto: ^3.0.3
  dio: ^5.4.0
  dots_indicator: ^3.0.0
  feather_icons: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  http: ^1.2.0
  persistent_bottom_nav_bar: ^5.0.2
  provider: ^6.1.1
  signed_spacing_flex: ^1.1.0
  velocity_bloc: ^1.1.4
  velocity_x: ^4.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
